//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Global {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Global() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Cinema.IVH7B4.WebUI.Resources.Global", typeof(Global).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Arrangement {
            get {
                return ResourceManager.GetString("Arrangement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Contact_Text_travel {
            get {
                return ResourceManager.GetString("Contact_Text_travel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Contact_Travel_directions {
            get {
                return ResourceManager.GetString("Contact_Travel_directions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string ContactAge {
            get {
                return ResourceManager.GetString("ContactAge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string ContactInterest {
            get {
                return ResourceManager.GetString("ContactInterest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string ContactLocation {
            get {
                return ResourceManager.GetString("ContactLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string ContactName {
            get {
                return ResourceManager.GetString("ContactName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string ContactNewsLetter_Text {
            get {
                return ResourceManager.GetString("ContactNewsLetter_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string ContactSignUp {
            get {
                return ResourceManager.GetString("ContactSignUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string CreditCard_CardType {
            get {
                return ResourceManager.GetString("CreditCard_CardType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string CreditCard_Cartexpiration {
            get {
                return ResourceManager.GetString("CreditCard_Cartexpiration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string CreditCard_CartHolder {
            get {
                return ResourceManager.GetString("CreditCard_CartHolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string CreditCard_CartNumber {
            get {
                return ResourceManager.GetString("CreditCard_CartNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string CreditCard_CartSecurity {
            get {
                return ResourceManager.GetString("CreditCard_CartSecurity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string FilmOverView_Age {
            get {
                return ResourceManager.GetString("FilmOverView_Age", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string FilmOverView_DateString {
            get {
                return ResourceManager.GetString("FilmOverView_DateString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string FilmOverView_Description {
            get {
                return ResourceManager.GetString("FilmOverView_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string FilmOverView_Description_Movie {
            get {
                return ResourceManager.GetString("FilmOverView_Description_Movie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string FilmOverView_Film3dNo {
            get {
                return ResourceManager.GetString("FilmOverView_Film3dNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string FilmOverView_Film3dYes {
            get {
                return ResourceManager.GetString("FilmOverView_Film3dYes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string FilmOverView_FilmBeginTime {
            get {
                return ResourceManager.GetString("FilmOverView_FilmBeginTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string FilmOverView_FilmDuration {
            get {
                return ResourceManager.GetString("FilmOverView_FilmDuration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string FilmOverView_FilmEndTime {
            get {
                return ResourceManager.GetString("FilmOverView_FilmEndTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string FilmOverView_FilmInfo {
            get {
                return ResourceManager.GetString("FilmOverView_FilmInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string FilmOverView_FilmRoom {
            get {
                return ResourceManager.GetString("FilmOverView_FilmRoom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string FilmOverView_Gerne_Action {
            get {
                return ResourceManager.GetString("FilmOverView_Gerne_Action", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string FilmOverView_Gerne_Children {
            get {
                return ResourceManager.GetString("FilmOverView_Gerne_Children", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string FilmOverView_Gerne_Comedy {
            get {
                return ResourceManager.GetString("FilmOverView_Gerne_Comedy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string FilmOverView_Langague {
            get {
                return ResourceManager.GetString("FilmOverView_Langague", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string FilmOverView_NoImage {
            get {
                return ResourceManager.GetString("FilmOverView_NoImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string FilmOverView_OrderTickets {
            get {
                return ResourceManager.GetString("FilmOverView_OrderTickets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string FilmOverView_SearchButton {
            get {
                return ResourceManager.GetString("FilmOverView_SearchButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string FilmOverView_Searchondate {
            get {
                return ResourceManager.GetString("FilmOverView_Searchondate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string FilmOverView_Searchonmovie {
            get {
                return ResourceManager.GetString("FilmOverView_Searchonmovie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string FilmOverView_Subs {
            get {
                return ResourceManager.GetString("FilmOverView_Subs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string FilmOverView_WeekDayFriday {
            get {
                return ResourceManager.GetString("FilmOverView_WeekDayFriday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string FilmOverView_WeekDayMonday {
            get {
                return ResourceManager.GetString("FilmOverView_WeekDayMonday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string FilmOverView_WeekDaySaterday {
            get {
                return ResourceManager.GetString("FilmOverView_WeekDaySaterday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string FilmOverView_WeekDaySunday {
            get {
                return ResourceManager.GetString("FilmOverView_WeekDaySunday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string FilmOverView_WeekDayThursday {
            get {
                return ResourceManager.GetString("FilmOverView_WeekDayThursday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string FilmOverView_WeekDayTuesday {
            get {
                return ResourceManager.GetString("FilmOverView_WeekDayTuesday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string FilmOverView_WeekDayWednesday {
            get {
                return ResourceManager.GetString("FilmOverView_WeekDayWednesday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string FIltered_films_Director {
            get {
                return ResourceManager.GetString("FIltered_films_Director", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Filtered_Films_FirstMoviesAfter {
            get {
                return ResourceManager.GetString("Filtered_Films_FirstMoviesAfter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Filtered_FIlms_Ordertickets {
            get {
                return ResourceManager.GetString("Filtered_FIlms_Ordertickets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Filtered_Films_Protagonist {
            get {
                return ResourceManager.GetString("Filtered_Films_Protagonist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Filtered_Films_Results {
            get {
                return ResourceManager.GetString("Filtered_Films_Results", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string HeaderLocation {
            get {
                return ResourceManager.GetString("HeaderLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string ING_Payment_Password {
            get {
                return ResourceManager.GetString("ING_Payment_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string ING_Payment_UserName {
            get {
                return ResourceManager.GetString("ING_Payment_UserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string LadiesNightText {
            get {
                return ResourceManager.GetString("LadiesNightText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string NavBar_Theatres {
            get {
                return ResourceManager.GetString("NavBar_Theatres", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string NavBar_Rate
        {
            get
            {
                return ResourceManager.GetString("NavBar_Rate", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string OrderSummary_ChildTicket {
            get {
                return ResourceManager.GetString("OrderSummary_ChildTicket", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string OrderSummary_NormalTicket {
            get {
                return ResourceManager.GetString("OrderSummary_NormalTicket", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string OrderSummary_OrderView {
            get {
                return ResourceManager.GetString("OrderSummary_OrderView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string OrderSummary_Price {
            get {
                return ResourceManager.GetString("OrderSummary_Price", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string OrderSummary_SeniorTicket {
            get {
                return ResourceManager.GetString("OrderSummary_SeniorTicket", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string OrderSummary_StudentTicket {
            get {
                return ResourceManager.GetString("OrderSummary_StudentTicket", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string OrderSummary_TotalPrice {
            get {
                return ResourceManager.GetString("OrderSummary_TotalPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Payment_PaymentIdealTitle {
            get {
                return ResourceManager.GetString("Payment_PaymentIdealTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Payment_PaymentMethodTitle {
            get {
                return ResourceManager.GetString("Payment_PaymentMethodTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string PinView_BackButton {
            get {
                return ResourceManager.GetString("PinView_BackButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string PinView_CancelCheckout {
            get {
                return ResourceManager.GetString("PinView_CancelCheckout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string PinView_CheckoutAt {
            get {
                return ResourceManager.GetString("PinView_CheckoutAt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string PinView_CheckoutFilm {
            get {
                return ResourceManager.GetString("PinView_CheckoutFilm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string PinView_CheckoutInfo {
            get {
                return ResourceManager.GetString("PinView_CheckoutInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string PinView_CompleteCheckout {
            get {
                return ResourceManager.GetString("PinView_CompleteCheckout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string PopCornText {
            get {
                return ResourceManager.GetString("PopCornText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string RateOverView_65Price {
            get {
                return ResourceManager.GetString("RateOverView_65Price", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string RateOverView_ChildPrice {
            get {
                return ResourceManager.GetString("RateOverView_ChildPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string RateOverView_Next {
            get {
                return ResourceManager.GetString("RateOverView_Next", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string RateOverView_NextButton {
            get {
                return ResourceManager.GetString("RateOverView_NextButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string RateOverView_NormalPrice {
            get {
                return ResourceManager.GetString("RateOverView_NormalPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string RateOverView_NumberOfFreeSeats {
            get {
                return ResourceManager.GetString("RateOverView_NumberOfFreeSeats", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string RateOverView_Quantity {
            get {
                return ResourceManager.GetString("RateOverView_Quantity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string RateOverView_StudentPrice {
            get {
                return ResourceManager.GetString("RateOverView_StudentPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string RateOverView_Tickets {
            get {
                return ResourceManager.GetString("RateOverView_Tickets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string SelectBioscoop {
            get {
                return ResourceManager.GetString("SelectBioscoop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string SummaryView_Checkout {
            get {
                return ResourceManager.GetString("SummaryView_Checkout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string SummaryView_FilmDate {
            get {
                return ResourceManager.GetString("SummaryView_FilmDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string SummaryView_FilmInformation {
            get {
                return ResourceManager.GetString("SummaryView_FilmInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string SummaryView_FilmRowNumber {
            get {
                return ResourceManager.GetString("SummaryView_FilmRowNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string SummaryView_FilmSeatNumber {
            get {
                return ResourceManager.GetString("SummaryView_FilmSeatNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string SummaryView_FilmTitle {
            get {
                return ResourceManager.GetString("SummaryView_FilmTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string SummaryView_Freeseat {
            get {
                return ResourceManager.GetString("SummaryView_Freeseat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string SummaryView_Selectedseat {
            get {
                return ResourceManager.GetString("SummaryView_Selectedseat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string SummaryView_Takenseat {
            get {
                return ResourceManager.GetString("SummaryView_Takenseat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Ticket_backtoHome {
            get {
                return ResourceManager.GetString("Ticket_backtoHome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Ticket_PrintCode {
            get {
                return ResourceManager.GetString("Ticket_PrintCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Ticket_PrintCodeText {
            get {
                return ResourceManager.GetString("Ticket_PrintCodeText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Ticket_PrintTicket {
            get {
                return ResourceManager.GetString("Ticket_PrintTicket", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Ticket_ThanksOrderTitle {
            get {
                return ResourceManager.GetString("Ticket_ThanksOrderTitle", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Ticket_YourReservationCode {
            get { return ResourceManager.GetString("Ticket_YourReservationCode", resourceCulture); }
        }

        /// <summary>
                    ///   Looks up a localized string similar to .
                    /// </summary>
        public static string Current_filmWeek {
            get {
                return ResourceManager.GetString("Current_filmWeek", resourceCulture);
            }
        }
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Payment_PaymInTheatrhe {
            get {
                return ResourceManager.GetString("Payment_PaymInTheatrhe", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Pay_AfterPayConfirm {
            get {
                return ResourceManager.GetString("Pay_AfterPayConfirm", resourceCulture);
            }
        }
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Pay_AfterPayChosetoPay {
            get {
                return ResourceManager.GetString("Pay_AfterPayChosetoPay", resourceCulture);
            }
        }
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Pay_AfterPayOrder {
            get {
                return ResourceManager.GetString("Pay_AfterPayOrder", resourceCulture);
            }
        }
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string CodeViewText {
            get {
                return ResourceManager.GetString("CodeViewText", resourceCulture);
            }
        }
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string GenreAdventure
        {
            get
            {
                return ResourceManager.GetString("GenreAdventure", resourceCulture);
            }
        }
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string GenreAnimation
        {
            get
            {
                return ResourceManager.GetString("GenreAnimation", resourceCulture);
            }
        }
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string GenreRomance
        {
            get
            {
                return ResourceManager.GetString("GenreRomance", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string FilmOverViewTime {
            get {
                return ResourceManager.GetString("FilmOverViewTime", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string FilterControllerToday {
            get {
                return ResourceManager.GetString("FilterControllerToday", resourceCulture);
            }
        }
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string FilmOverViewNoInformation {
            get {
                return ResourceManager.GetString("FilmOverViewNoInformation", resourceCulture);
            }
        }
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string FilmOverViewNoSubs {
            get {
                return ResourceManager.GetString("FilmOverViewNoSubs", resourceCulture);
            }
        }

    }
}
